### ISSUE TITLE
--limitBAMsortRAM 

### ISSUE THREAD

**Issue by a-zoon** [yyoshiaki/VIRTUS2#12]
Hi, 

When I try to run ./VIRTUS.PE.cwl I get the error 're-rerun STAR with --limitBAMsortRAM 90000000000 when it starts to sort the BAM files after the mapping during the step 'star_mapping_pe_human'. I tried to change the VIRTUS.PE.cwl and add -limitBAMsortRAM 90000000000, however it seems that is also requires sbg:x and sbg:y numbers. What do these numbers stand for and how can I add the --limitBAMsortRAM to the VIRTUS.PE.cwl file with the right sbg:x and sbg:y numbers?

Anne

**Comment by yyoshiaki** [comment]
Hi Anne,

Sbg is a meaningless number that is used for just positions for tools in Rabix composer, a GUI tool for editing CWL files, and I think you don't need to add them. Rather, you need to add input parameters to `tool/star/star_mapping-pe/star_mapping-pe.cwl` as well.

Yoshi

**Comment by a-zoon** [comment]
Hi Yoshi, 

I also have added the input parameters in the star_mapping-pe.cwl file. I get this message, so it seems to me that some source information is needed. 
![thumbnail_image](https://user-images.githubusercontent.com/122974614/213165053-ca6b537d-a86d-481d-9d05-2f236c4a87a4.png)

**Comment by yyoshiaki** [comment]
I see, so, how about adding random numbers?

For example,

```
    'sbg:x':0
    'sbg:y': 0
```

**Comment by a-zoon** [comment]
Then I get this message: 

![image](https://user-images.githubusercontent.com/122974614/213164484-dc72e6a9-bbd0-410a-a399-2c55e8158c3b.png)

**Comment by a-zoon** [comment]
Then I got this message 
![image](https://user-images.githubusercontent.com/122974614/213167045-45d4981e-8735-48ed-ace8-6997bcb5502e.png)

**Comment by yyoshiaki** [comment]
I can't follow your procedures. Can you for example share modified cwl files?

Also, you are specifying 90Gb RAM as the limit size, but I assume that if your computer has 90Gb RAM, you can run VIRTUS2 with default parameters without modifying the RAM limit. How much amount of memory are you using and what is your environment?
