### ISSUE TITLE
IGV

### ISSUE THREAD

**Issue by km-2021** [yyoshiaki/VIRTUS2#13]
Is it possible to visualize the virusAligned.filtered.sortedByCoord.out.bam file in IGV? I created a bai file in samtools and tried to read it, but it gives an error.

**Comment by yyoshiaki** [comment]
It may be possible to show virusAligned.filtered.sortedByCoord.out.bam in IGV, but I have not tried it. I usually re-align reads with an index for the viruses that have been hit.
