### ISSUE TITLE
createindex

### ISSUE THREAD

**Issue by inagaki-s** [yyoshiaki/VIRTUS2#14]
" cwltool createindex.cwl https://raw.githubusercontent.com/yyoshiaki/VIRTUS2/master/workflow/createindex.job.yaml"
I tried to run createindex in the workflow directory, but I get the following error. What could be the cause?

ERROR Tool definition failed validation:
Error fetching https://raw.githubusercontent.com/yyoshiaki/VIRTUS2/master/workflow/createindex.job.yaml: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yyoshiaki/VIRTUS2/master/workflow/createindex.job.yaml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0eca94e6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by yyoshiaki** [comment]
This looks like a network issue in downloading the input yaml file.
you can manually download the YAML file (https://raw.githubusercontent.com/yyoshiaki/VIRTUS2/master/workflow/createindex.job.yaml) and specify it instead of the URL, such as `cwltool createindex.cwl createindex.job.yaml`.

**Comment by inagaki-s** [comment]
I was able to solve the problem. Thank you very much.
