### ISSUE TITLE
Gene counts

### ISSUE THREAD

**Issue by lukewgarratt** [yyoshiaki/VIRTUS2#18]
Hello,
What is the best approach to also generate gene counts for the human alignments and summarise into a csv file?
If I modify star_mapping-pe.cwl with "--quantmode GeneCounts" then that will try to generate counts for both the human and virus data, correct?
I notice that the index run does not download gtf files or generate a geneInfo.tab that STAR expects to find.
Thank you

**Comment by lukewgarratt** [comment]
Alright, I've created my own solution by incorporating the salmon steps from the first VIRTUS into a hybrid pipeline. Doesn't add too much computation time (gone from ~63 min per PE sample to ~70 min).

**Comment by yyoshiaki** [comment]
Thank you!
