### ISSUE TITLE
Question about indexing genomes while using singularity

### ISSUE THREAD

**Issue by egnst** [yyoshiaki/VIRTUS2#21]
I don't have root permissions, so I'm trying to use singularity instead of docker. I'm just getting started, so I'm running createindex.cwl. 

I used the command:

 ./createindex.cwl --dir_name_STAR_human STAR_index_human --dir_name_STAR_virus STAR_index_virus --output_name_genomefasta_human GRCh38.p13.genome.fa.gz --output_name_virus viruses.fasta --runThreadN 40 --url_genomefasta_human ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/GRCh38.p13.genome.fa.gz --url_virus https://raw.githubusercontent.com/yyoshiaki/VIRTUS2/master/data/viruses.fasta 

I got the error:  

Workflow or tool uses unsupported feature:
Docker is required to run this tool: docker executable is not available

I tried to add the option --singularity, and got:

 error: unrecognized arguments: --singularity

How do I index my genome while I'm dependent on singularity? Thanks for your help!

**Comment by yyoshiaki** [comment]
Hi, can you check cwltool works well with singularity using the official tutorial? https://github.com/common-workflow-language/cwltool#using-singularity

**Comment by egnst** [comment]
I just ran the Singularity tutorial with no changes, and  it looks like it works. It says "Final process status is success"

This is the specific thing I ran: 

cwltool --singularity https://github.com/common-workflow-language/common-workflow-language/raw/main/v1.0/v1.0/cat3-tool-mediumcut.cwl https://github.com/common-workflow-language/common-workflow-language/raw/main/v1.0/v1.0/cat-job.json

**Comment by egnst** [comment]
Hi Yoshiyaki, 

I'm only trying to use hg38 plus the default viruses included in the package (I care the most about HPV). I was thinking that maybe one workaround might be if you knew a way to post reference genomes that had already been indexed. I know it's kind of a pain to host large files so that they can be downloaded online, but maybe that would be easier as a short term solution? Do you already have default indexed genomes posted somewhere?

**Comment by egnst** [comment]
We fixed the issue by manually editing the first line of ~/VIRTUS2/workflow/createindex.cwl:

from:  #!/usr/bin/env cwltool
to:  #!/usr/bin/env -S cwltool --singularity
