### ISSUE TITLE
Query is marked as paired, but its mate does not occur next to it in your BAM file. Skipping.

### ISSUE THREAD

**Issue by ppark123** [yyoshiaki/VIRTUS2#24]
Hello, whenever I run any paired RNA-seq dataset including the sample ERR3240275 dataset, it outputs many of the same warning "*****WARNING: Query ERR3240275.162499 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping." with a different query number each time. I do get the same output as the table shown in the README.md, but will this have any effect on the final output of VIRTUS2?

**Comment by yyoshiaki** [comment]
Sorry for my late reply. You can ignore the warnings.  In the later step, VIRTUS2 selects only paired reads.
