### ISSUE TITLE
Running this on an hpc with no docker installed

### ISSUE THREAD

**Issue by KevinMaroney** [yyoshiaki/VIRTUS2#25]
Hello, I tried to run your tutorial after you redirected me here from Virtect and VIRTUS v1, but am running into an issue: my fasta files are quite large and so this necessitates me using a high performance computing cluster where I do not have installation privileges. I tried to make a conda environment with docker installed (pip install docker) but when I attempt to download the index files as you said:
./createindex.cwl https://raw.githubusercontent.com/yyoshiaki/VIRTUS2/master/workflow/createindex.job.yaml

I get the following error:
INFO /data/user/kmaroney/.conda/envs/Virtus/bin/cwltool 3.1.20230624081518
INFO Resolved './workflow/createindex.cwl' to 'file:///data/user/home/kmaroney/programs/VIRTUS2/workflow/createindex.cwl'
INFO [workflow ] start
INFO [workflow ] starting step mkdir_virus
INFO [step mkdir_virus] start
ERROR Workflow or tool uses unsupported feature:
Docker is required to run this tool: docker executable is not available

I don't use Docker at all - is there a workaround to this or do I have to call it from within my conda environment before running the command? (It seems to be installed from pip install docker?).

Sorry if these are very basic questions for you. Thanks for your help :)

**Comment by yyoshiaki** [comment]
Whether you can use docker or not in your HPC depends on your system. In most cases, for HPC, only administrators can install docker, so it would be nice to ask the administrators about that.
You can use singularity instead of docker though the situation is similar.

**Comment by KevinMaroney** [comment]
I suppose what I'm wondering is if there is a simple command to download all the references without Docker? Or is everything set up through a Docker container which is called by this code and it has to be through Docker?

**Comment by yyoshiaki** [comment]
It is theoretically possible to download and install all tools manually, but I don't definitely recommend it.
If you use docker or singularity, you don't have to set up individual tools.

**Comment by KevinMaroney** [comment]
I completely understand, but my problem is that I don’t have docker or singularity installed on the cluster where my data is stored. I’ve asked them if they can install docker as you suggested. I hope they can.

Sincerely,
Kevin Maroney

M.S. Biotechnology
University of California
PhD student
University of Alabama at Birmingham

________________________________

**Comment by yyoshiaki** [comment]
Good luck, Docker/singularity would greatly improve your bioinformatics life!
