### ISSUE TITLE
About summary.csv

### ISSUE THREAD

**Issue by nmotisk** [yyoshiaki/VIRTUS2#31]
When I run VIRTUS2, I think it creates a file called summary.csv, but for my data set, the contents are empty.
However, when I write a heatmap, etc., it seems to be outputting the data.

What is the cause of the empty summary.csv?

**Comment by yyoshiaki** [comment]
Most probably, your dataset does not contain detectable viral reads.

**Comment by gailrosen** [comment]
I never get a heatmap -- what is the file name?  Can I write the heatmap to a file?
