### ISSUE TITLE
Thousands of weird warnings in the output of VIRTUS2

### ISSUE THREAD

**Issue by xapple** [yyoshiaki/VIRTUS2#36]
I've been using VIRTUS2 in paired end mode on a couple of datasets and I've noticed that in the standard output of the process there are thousands of line like these:

    *****WARNING: Query run.24568966 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24569628 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24569637 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24569737 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24572520 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24572774 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24578352 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24578533 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24578546 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24582531 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24583555 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24583557 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24583558 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24583559 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24584286 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24584761 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24591733 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24596860 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24596861 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24597449 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24600876 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24603228 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
    *****WARNING: Query run.24605922 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.

As well as thousands of lines like these:

    [W::sam_parse1] unrecognized mate reference name "GL000251.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000255.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000255.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000255.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000251.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000251.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000255.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr3"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000252.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000255.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000254.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "GL000255.2"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr6"; treated as unmapped
    [W::sam_parse1] unrecognized mate reference name "chr6"; treated as unmapped

The pipeline still completes, but should I be worried that it just ignored most of my sequences silently ?

**Comment by yyoshiaki** [comment]
Please ignore these alerts!
