### ISSUE TITLE
No module named 'seaborn.external.six'

### ISSUE THREAD

**Issue by km-2021** [yyoshiaki/VIRTUS2#5]
Hi,

When I run wrapper.py, I get an error ''ModuleNotFoundError: No module named 'seaborn.external.six'. 
How to fix it?

**Comment by yyoshiaki** [comment]
Hi, which version of seaborn are you using?

**Comment by km-2021** [comment]
Thank you for your reply,

Seaborn version is 0.11.2.

**Comment by yyoshiaki** [comment]
Thank you, could you please try to downgrade seaborn?
Actually, we have noticed that seaborn version >=0.12 will cause this error (https://github.com/mwaskom/seaborn/commit/f76e5abbeb747c00c18df321a7211b754c016d8a ), but 0.11.2 in our environments are working well.

**Comment by km-2021** [comment]
Thank you for your reply,

Wrapper.py worked well with seaborn v.0.10.0.

**Comment by yyoshiaki** [comment]
Thank you!

**Comment by yyoshiaki** [comment]
We fixed this bug in v2.0.1 and released it now.
https://github.com/yyoshiaki/VIRTUS2/releases/tag/v2.0.1
