### ISSUE TITLE
Absolute path 

### ISSUE THREAD

**Issue by km-2021** [yyoshiaki/VIRTUS2#7]
Hi,

I specified an absolute path with "DIR_INDEX_ROOT=/absolute/path/to/dir/of/indeices/created", but I get an error "invalid path to VIRTUS. try to change --VIRTUSDir to the absolute path." in running Virtus_wrapper.py. How to fix it?

**Comment by yyoshiaki** [comment]
https://github.com/yyoshiaki/VIRTUS2/blob/master/wrapper/run.sh

As this script, can you specify the path?

**Comment by km-2021** [comment]
Thanks,

This error is solved.
However, I get an error: ModuleNotFoundError: No module named 'scattermap'.

**Comment by yyoshiaki** [comment]
Did you move VIRTUS_wrapper.py alone? If so, VIRTUS_wrapper.py and scattermap.py should be in the same directory.

**Comment by km-2021** [comment]
Thanks,

The pipeline worked well. Thanks a lot!
